### ISSUE TITLE
cp: cannot stat 'bench/nb_cores' when running `nix-build`

### ISSUE THREAD

**Issue by NickGeek** [deepsea-inria/heartbeat#1]
Hi, I'm interested in running the benchmarks but I encountered this error when running `nix-build`:
```
cp: cannot stat 'bench/nb_cores': No such file or directory
error: builder for '/nix/store/aha5f6909fg470vfh87fg88zjygp3205-heartbeat-v1.0-pldi.drv' failed with exit code 1
```

**Comment by mikerainey** [comment]
Hi Nick, I've just now come across notifications for these issues. I'll be looking into fixes in the next couple of days. The fix for this issue should be fairly easy, but the input files might require some way around ipfs.

**Comment by NickGeek** [comment]
Thanks, this one is not a big one because I can manually create the file. The IPFS dependency is a bit complex because the one system I have access to with 128GB of RAM does not have access to IPFS.

**Comment by mikerainey** [comment]
Hi Nick, I've just committed a fix for this issue.
